
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftIFTRUE FALSE IF THEN ELSE ZERO VARIABLE BACKSLASH NUMBER DOT 2DOTS OPENPARENTHESIS CLOSEPARENTHESIS SUCC PRED ISZERO TYPE ARROWexpression : exprexpr : ZEROexpr : PRED OPENPARENTHESIS expr CLOSEPARENTHESISexpr : SUCC OPENPARENTHESIS expr CLOSEPARENTHESISexpr : ISZERO OPENPARENTHESIS expr CLOSEPARENTHESISexpr : NUMBERexpr : TRUEexpr : FALSEexpr : IF expr THEN expr ELSE expr %prec IF'
    
_lr_action_items = {'CLOSEPARENTHESIS':([1,4,5,9,15,16,17,19,20,21,24,],[-8,-6,-2,-7,19,20,21,-4,-3,-5,-9,]),'THEN':([1,4,5,9,14,19,20,21,24,],[-8,-6,-2,-7,18,-4,-3,-5,-9,]),'OPENPARENTHESIS':([3,6,7,],[11,12,13,]),'FALSE':([0,10,11,12,13,18,23,],[1,1,1,1,1,1,1,]),'PRED':([0,10,11,12,13,18,23,],[6,6,6,6,6,6,6,]),'ZERO':([0,10,11,12,13,18,23,],[5,5,5,5,5,5,5,]),'NUMBER':([0,10,11,12,13,18,23,],[4,4,4,4,4,4,4,]),'ELSE':([1,4,5,9,19,20,21,22,24,],[-8,-6,-2,-7,-4,-3,-5,23,-9,]),'SUCC':([0,10,11,12,13,18,23,],[3,3,3,3,3,3,3,]),'ISZERO':([0,10,11,12,13,18,23,],[7,7,7,7,7,7,7,]),'$end':([1,2,4,5,8,9,19,20,21,24,],[-8,-1,-6,-2,0,-7,-4,-3,-5,-9,]),'TRUE':([0,10,11,12,13,18,23,],[9,9,9,9,9,9,9,]),'IF':([0,10,11,12,13,18,23,],[10,10,10,10,10,10,10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,10,11,12,13,18,23,],[2,14,15,16,17,22,24,]),'expression':([0,],[8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expr','expression',1,'p_expression_initial','parser.py',222),
  ('expr -> ZERO','expr',1,'p_expr_zero','parser.py',227),
  ('expr -> PRED OPENPARENTHESIS expr CLOSEPARENTHESIS','expr',4,'p_expr_pred','parser.py',231),
  ('expr -> SUCC OPENPARENTHESIS expr CLOSEPARENTHESIS','expr',4,'p_expr_succ','parser.py',235),
  ('expr -> ISZERO OPENPARENTHESIS expr CLOSEPARENTHESIS','expr',4,'p_expr_is_zero','parser.py',239),
  ('expr -> NUMBER','expr',1,'p_expr_number','parser.py',244),
  ('expr -> TRUE','expr',1,'p_expr_true','parser.py',249),
  ('expr -> FALSE','expr',1,'p_expr_false','parser.py',257),
  ('expr -> IF expr THEN expr ELSE expr','expr',6,'p_expr_if_then_else','parser.py',261),
]
