
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftMINUSleftPLUSleftTIMESrightUMINUSNUMBER PLUS TIMES MINUSexpression : expression PLUS expressionexpression : expression TIMES expressionexpression : expression MINUS expressionexpression : MINUS expression %prec UMINUSexpression : NUMBER'
    
_lr_action_items = {'$end':([1,2,7,8,9,10,],[-5,0,-4,-1,-3,-2,]),'PLUS':([1,2,7,8,9,10,],[-5,4,-4,-1,4,-2,]),'MINUS':([0,1,2,3,4,5,6,7,8,9,10,],[3,-5,5,3,3,3,3,-4,-1,-3,-2,]),'TIMES':([1,2,7,8,9,10,],[-5,6,-4,6,6,-2,]),'NUMBER':([0,3,4,5,6,],[1,1,1,1,1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,3,4,5,6,],[2,7,8,9,10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS expression','expression',3,'p_expression_plus','parser.py',32),
  ('expression -> expression TIMES expression','expression',3,'p_expression_times','parser.py',36),
  ('expression -> expression MINUS expression','expression',3,'p_expression_minus','parser.py',40),
  ('expression -> MINUS expression','expression',2,'p_expression_uminus','parser.py',44),
  ('expression -> NUMBER','expression',1,'p_term_number','parser.py',49),
]
